### ISSUE TITLE
Occurred While Resolving Message.

### ISSUE THREAD

**Issue by MertcanGokgoz** [Texnomic/SecureDNS#163]
Hello,

The application works very well. but I have a little problem like this. Most of the time I see the following errors on the terminal, is this normal? There is no other output than these lines. 

Thanks

```
[12:30:57 ERR] System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 217
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 42
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 63
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 36
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 68
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 91
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
   at Texnomic.DNS.Servers.ProxyServer.ResolveAsync() in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\ProxyServer.cs:line 205 Occurred While Resolving Message.
System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 217
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 42
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 63
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 36
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 68
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 91
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
   at Texnomic.DNS.Servers.ProxyServer.ResolveAsync() in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\ProxyServer.cs:line 205
[12:30:57 ERR] System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 217
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 42
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 63
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 36
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 68
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 91
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
   at Texnomic.DNS.Servers.ProxyServer.ResolveAsync() in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\ProxyServer.cs:line 205 Occurred While Resolving Message.
System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 217
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 42
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 63
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 36
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 68
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 91
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
```

**Comment by Texnomic** [comment]
Yes, It is normal. It is simply a Timeout Error when DNS Messages aren't sent/received within allotted timeframe.
