### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by crssi** [Texnomic/SecureDNS#363]
I get Fatals and Errors.
Also every query I make has timeouts before resolving

**NSLOOKUP**
```
> google.com
Server:  localhost
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4001:80e::200e
          142.250.185.110
```

**SDNS OUTPUT**
```
       ________                                         _____
       ___  __/_____ ____  _________ ______ _______ ___ ___(_)_______
       __  /   _  _ \__  |/_/__  __ \_  __ \__  __ `__ \__  / _  ___/
       _  /    /  __/__>  <  _  / / // /_/ /_  / / / / /_  /  / /__
       /_/     \___/ /_/|_|  /_/ /_/ \____/ /_/ /_/ /_/ /_/   \___/

       ________                                   ________ _____   __________
       __  ___/_____ ___________  _______________ ___  __ \___  | / /__  ___/
       _____ \ _  _ \_  ___/_  / / /__  ___/_  _ \__  / / /__   |/ / _____ \
       ____/ / /  __// /__  / /_/ / _  /    /  __/_  /_/ / _  /|  /  ____/ /
       /____/  \___/ \___/  \__,_/  /_/     \___/ /_____/  /_/ |_/   /____/


[12:43:55 INF] Server Started with 12 Threads. Listening On 127.0.0.1:53
[12:43:55 INF] Application started. Press Ctrl+C to shut down.
[12:43:55 INF] Hosting environment: Production
[12:43:55 INF] Content root path: C:\Program Files\Texnomic\Texnomic SecureDNS Terminal\
[12:44:37 FTL] Fatal {"LineNumber": 2, "LinePosition": 49, "SourceUri": "", "Message": "'src' is an unexpected token. The expected token is '='. Line 2, position 49.", "TargetSite": "Void MoveNext()", "StackTrace": "   at Texnomic.FilterLists.FilterListsClient.GetListsAsync() in D:\\Repositories\\Texnomic.SecureDNS\\Texnomic.FilterLists\\FilterListsClient.cs:line 39\r\n   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.GetFilterListsAsync(Int32[] IDs) in D:\\Repositories\\Texnomic.SecureDNS\\Texnomic.DNS.Servers\\Middlewares\\FilterListsMiddleware.cs:line 125\r\n   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.InitializeAsync(Int32[] IDs) in D:\\Repositories\\Texnomic.SecureDNS\\Texnomic.DNS.Servers\\Middlewares\\FilterListsMiddleware.cs:line 76", "Data": [], "InnerException": null, "HelpLink": null, "Source": "Texnomic.FilterLists", "HResult": -2146232000, "$type": "XmlException"} Occurred While Initializing FilterLists.
[12:44:40 INF] Resolved {"ID": 5, "MessageType": "Response", "OperationCode": "Query", "AuthoritativeAnswer": "Cache", "Truncated": false, "RecursionDesired": true, "RecursionAvailable": true, "Zero": 0, "AuthenticatedData": false, "CheckingDisabled": false, "ResponseCode": "NoError", "QuestionsCount": 1, "Questions": [{"Domain": "google.com", "Type": "A", "Class": "Internet", "$type": "Question"}], "AnswersCount": 1, "Answers": [{"TimeToLive": "00:02:29", "Record": {"Address": "142.250.186.142", "$type": "A"}, "Domain": "google.com", "Type": "A", "Class": "Internet", "$type": "Answer"}], "AuthorityCount": 0, "Authority": [], "AdditionalCount": 0, "Additional": [], "$type": "Message"} For google.com with NoError To 127.0.0.1:57916.
[12:44:40 INF] Resolved {"ID": 6, "MessageType": "Response", "OperationCode": "Query", "AuthoritativeAnswer": "Cache", "Truncated": false, "RecursionDesired": true, "RecursionAvailable": true, "Zero": 0, "AuthenticatedData": false, "CheckingDisabled": false, "ResponseCode": "NoError", "QuestionsCount": 1, "Questions": [{"Domain": "google.com", "Type": "AAAA", "Class": "Internet", "$type": "Question"}], "AnswersCount": 1, "Answers": [{"TimeToLive": "00:03:45", "Record": {"Address": "2a00:1450:4001:80f::200e", "$type": "AAAA"}, "Domain": "google.com", "Type": "AAAA", "Class": "Internet", "$type": "Answer"}], "AuthorityCount": 0, "Authority": [], "AdditionalCount": 0, "Additional": [], "$type": "Message"} For google.com with NoError To 127.0.0.1:57918.
[12:44:41 ERR] System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 192
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 37
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 47
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 29
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 66
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 84
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
   at Texnomic.DNS.Servers.ProxyServer.ResolveAsync() in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\ProxyServer.cs:line 205 Occurred While Resolving Message.
System.TimeoutException: The operation has timed out.
   at Texnomic.SecureDNS.Protocols.DNSCrypt.ResolveAsync(Byte[] Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\DNSCrypt.cs:line 192
   at Texnomic.SecureDNS.Protocols.Protocol.ResolveAsync(IMessage Query) in D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols\Protocol.cs:line 37
   at Texnomic.DNS.Servers.Middlewares.ResolverMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ResolverMiddleware.cs:line 47
   at Texnomic.DNS.Servers.Middlewares.ENSMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\ENSMiddleware.cs:line 29
   at Texnomic.DNS.Servers.Middlewares.FilterListsMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\FilterListsMiddleware.cs:line 66
   at Texnomic.DNS.Servers.Middlewares.HostTableMiddleware.Run(IMessage Message, Func`2 Next) in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\Middlewares\HostTableMiddleware.cs:line 84
   at PipelineNet.ChainsOfResponsibility.AsyncResponsibilityChain`2.Execute(TParameter parameter)
   at Texnomic.DNS.Servers.ProxyServer.ResolveAsync() in D:\Repositories\Texnomic.SecureDNS\Texnomic.DNS.Servers\ProxyServer.cs:line 205
```

Also if I add filterlist 1734... that is Badmojr PRO and make a DNS query for something that is listed on, I would expect response as 0.0.0.0 instead of real IP.

Any suggestions?
Thank you 😄

**Comment by crssi** [comment]
I also see reference to folder `D:\Repositories\Texnomic.SecureDNS\Texnomic.SecureDNS.Protocols` in the upper logs, but there is no drive D.

**Comment by Texnomic** [comment]
I can see two issues here. Both are fixed in `master` but not in `releases`. Can you build from source and confirm if you still face the same issues ?

**Comment by crssi** [comment]
When the new release is to be expected?

Thank you and cheers

**Comment by Celuni** [comment]
I'm interested in this app but the last build was 2020 and that's turning me off.
Release ETA?

**Comment by Texnomic** [comment]
New release now available https://github.com/Texnomic/SecureDNS/releases/tag/v0.4-alpha

Let me know if you still having any issues.
